on:
  - push

name: Build
jobs:
  build:
    strategy:
      matrix:
        go-version:
          - 1.21.x
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - run: go version
      - run: go build -v -race ./...
